cv_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('opencv_webapp.urls')),

]

opencv_webapp/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'opencv_webapp'
urlpatterns = [    path('', views.first_view, name='first_view'),    path('simple_upload/', views.simple_upload, name='simple_upload'),    path('detect_face/', views.detect_face, name='detect_face'),]urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opencv_webapp/models.py
from django.db import models

class ImageUploadModel(models.Model):
 
    description = models.CharField(max_length=255, blank=True) 
    document = models.ImageField(upload_to='images/%Y/%m/%d') 
    uploaded_at = models.DateTimeField(auto_now_add=True)

opencv_webapp/forms.py
from django import forms
from .models import ImageUploadModel

class SimpleUploadForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.ImageField()

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageUploadModel
        fields = ('description', 'document', ) 

opencv_webapp/views.py
from django.shortcuts import render, redirect
from .forms import SimpleUploadForm, ImageUploadForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .cv_functions import cv_detect_face


def first_view(request):
    return render(request, 'opencv_webapp/first_view.html', {})

def simple_upload(request):
    if request.method == 'POST':
        form = SimpleUploadForm(request.POST, request.FILES)
        if form.is_valid():
            myfile = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            context = {'form': form, 'uploaded_file_url': uploaded_file_url}
            return render(request, 'opencv_webapp/simple_upload.html', context)
    else:
        form = SimpleUploadForm()
        context = {'form': form}
        return render(request, 'opencv_webapp/simple_upload.html', context)

def detect_face(request):
    if request.method == 'POST' :
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            imageURL = settings.MEDIA_URL + form.instance.document.name
            cv_detect_face(settings.MEDIA_ROOT_URL + imageURL) 
            return render(request, 'opencv_webapp/detect_face.html', {'form':form, 'post':post})
    else:
        form = ImageUploadForm()
        return render(request, 'opencv_webapp/detect_face.html', {'form':form})



 

opencv_webapp/templates/opencv_webapp/detect_face.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    {% if post %}
    <!-- post.document : ImageUploadModel Class에 선언되어 있는 "document"에 해당 (브라우저 확인) -->
    <img src="{{ post.document.url }}">
    <p>Uploaded file @ : <a href="{{ post.document.url }}">{{ post.document }}</a></p>
    {% endif %}
    <p><a href="{% url 'opencv_webapp:detect_face' %}">Return to home</a></p>
</body>
</html>

opencv_webapp/templates/opencv_webapp/first_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
</head>
<body>
    Hello world!
</body>
</html>

opencv_webapp/templates/opencv_webapp/simple_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
</head>
<body>
    <h1>Upload your image file.</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
    {% if uploaded_file_url %}
    <img src="{{ uploaded_file_url }}">
    <p>Uploaded file @ : <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}
    <p><a href="{% url 'opencv_webapp:simple_upload' %}">Return to home</a></p>
</body>
</html>